

/* AUTOGENERATED FILE - (generate_embedded_assets.py) - DO NOT MODIFY */                         
                         
#include "incbin_common.h"
INCBIN(www_zip, "www.zip");

/* END OF AUTOGENERATED FILE - (generate_embedded_assets.py) */
